### PR TITLE
Can't override axios headers for authorization

### LINKED ISSUE #251: Can't override axios headers for authorization
**Describe the bug**
Hethers uses axios under the hood to do it's polling.  This makes it difficult (impossible?) to integrate with mirror providers that require custom authorization headers.

Please allow overriding of axios options for requests, specifically for headers.

**Reproduction steps**
Any contract event listening.

**Environment:**
Everywhere

**Search Terms**
axios

### PR DESCRIPTION
**Pull request by ar-conmit**
Signed-off-by: Anton Rusev <anton.rusev.code@gmail.com>

**Description**:
* Extend provider options to pass additional headers to axios request

**Related issue(s)**:

Fixes #251 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: packages/tests/src.ts/utils.ts [hunk 1]
```diff
@@ -61,9 +61,103 @@ function equals(a: any, b: any): boolean {
...
     randomNumber,
-    equals
+    equals,
+    getAccounts,
+    getProviders,
+    getWallets
 }
+
+
+// const wallet = new hethers.Wallet({
```
Comment (natanasow) [inline packages/tests/src.ts/utils.ts:145]: Let's remove the commented section

File: packages/tests/src.ts/utils.ts [hunk 2]
```diff
@@ -61,9 +61,103 @@ function equals(a: any, b: any): boolean {
     return a === b;
 }
 
+
+const getAccounts = () => {
+    return {
```
Comment (natanasow) [inline packages/tests/src.ts/utils.ts:66]: The most usable accounts are [Alias ECDSA](
https://github.com/hashgraph/hedera-local-node/blob/main/src/hederaUtils.js#L5), let's add them here as well

**Review by natanasow — APPROVED** [review]
LG
