### PR TITLE
Fix: Change default cost of `ContractCallQuery` 

### LINKED ISSUE #224: Change default cost of `ContractCallQuery`

### PR DESCRIPTION
**Pull request by joan41868**
Signed-off-by: joan41868 <yoansredkov@gmail.com>

**Description**:

**Related issue(s)**:
None (yet).
Fixes #224 

**Notes for reviewer**:

This **PR** changes the default fee for a `ContractCallQuery` (`abstract-signer`, r. 190) . 

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: packages/tests/src.ts/test-contract.spec.ts [hunk 1]
```diff
@@ -21,10 +21,10 @@ const hederaEoa = {
 };
 
 describe("Test Contract Transaction Population", function() {
+    this.retries(3);
```
Comment (Daniel-K-Ivanov) [inline packages/tests/src.ts/test-contract.spec.ts:24]: Why is this required?

File: packages/tests/src.ts/test-contract.spec.ts [hunk 2]
```diff
@@ -154,6 +154,7 @@ describe("Test Contract Transaction Population", function() {
 });
 
 describe('Contract Events', function () {
+    this.retries(3);
```
Comment (Daniel-K-Ivanov) [inline packages/tests/src.ts/test-contract.spec.ts:157]: Why is this required?

File: packages/abstract-signer/src.ts/index.ts [hunk 3]
```diff
@@ -186,13 +187,12 @@ export abstract class Signer {
         } else {
             hederaTx.setContractId(to);
         }
-
-        // TODO: the exact amount here will be computed using getCost when it's implemented
-        const cost = 3;
+        const gasLimit = BigNumber.from(tx.gasLimit).toNumber();
+        const cost = DEFAULT_HEDERA_CALL_TX_FEE * 10 + gasLimit * CALL_GAS_PRICE_TINYBARS;
```
Comment (Daniel-K-Ivanov) [inline packages/abstract-signer/src.ts/index.ts:191]: nit: I think that it would be better to extract the `10` in a const above  and state that this is a buffer for fluctuating prices. We can multiple it by `20` as-well. Just to be sure that we won't brake someone in the case that 6 months from now, hbars have dropped in value or the user provides many `signatures` as part of his transaction (meaning that more will be charged for sig verification)

**Review by Daniel-K-Ivanov — CHANGES_REQUESTED** [review]

File: packages/abstract-signer/src.ts/index.ts [hunk 4]
```diff
@@ -188,11 +190,12 @@ export abstract class Signer {
             hederaTx.setContractId(to);
         }
         const gasLimit = BigNumber.from(tx.gasLimit).toNumber();
-        const cost = DEFAULT_HEDERA_CALL_TX_FEE * 10 + gasLimit * CALL_GAS_PRICE_TINYBARS;
+        const priorityCost = DEFAULT_HEDERA_CALL_TX_FEE * TX_FEE_BUFFER_MULTIPLIER;
```
Comment (Daniel-K-Ivanov) [inline packages/abstract-signer/src.ts/index.ts:193]: I am not sure that priorityCost is the best word for it... people might confuse it with "priority fee" as it is in ethereum

**Review by Daniel-K-Ivanov — CHANGES_REQUESTED** [review]

**Comment by joan41868** [comment]
https://github.com/hashgraph/hedera-mirror-node/issues/3486 - we should wait for this to go in production for the CI to pass.

**Comment by joan41868** [comment]
We should also wait for the fix to be deployed on testnet. This endpoint may serve as a check:
https://testnet.mirrornode.hedera.com/api/v1/contracts/0.0.29593659

**Review by natanasow — APPROVED** [review]
